name: 'Dependency Review'
on: [pull_request, push]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        if: ${{ github.base_ref }}
        uses: actions/dependency-review-action@v4